import "./globals.css";
import { Barlow, Fraunces } from "next/font/google";

const barlow = Barlow({
  weight: ["600"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-barlow",
});

const fraunces = Fraunces({
  weight: ["700", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-fraunces",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${barlow.variable} ${fraunces.variable}`}>
        {children}
      </body>
    </html>
  );
}
